# Netlify configuration

[build]
publish = "dist/"
command = "npm run build"

[build.environment]
NODE_VERSION = "22.13.1"

[build.processing.html]
pretty_urls = true

# Security headers as recommended by https://securityheaders.com
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer-when-downgrade"
Content-Security-Policy = "default-src 'self' 'unsafe-inline' giscus.app; worker-src 'self' blob:; base-uri 'none'; object-src 'none'"

# Cache static assets for 1 year
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000"
