# Netlify configuration

[build]
publish = "dist/"
command = "npm run build"

[build.environment]
NODE_VERSION = "21.6.1"

# Security headers as recommended by https://securityheaders.com
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer-when-downgrade"
Content-Security-Policy = "default-src 'self'"

# Cache static assets for 1 year
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000"
