import typography from "@tailwindcss/typography";
import defaultTheme from "tailwindcss/defaultTheme";

/**
 * Implement a fluid font size based on viewport width with a minimum size
 * of 16px and a maximum of 18px. This also affects all relative size
 * specifications which are directly or indirectly based on the base font
 * size. The result is a zoom effect of the whole layout.
 *
 * Generated by https://websemantics.uk/tools/responsive-font-calculator/
 * 16px @ 768px increasing to 18px @ 1024px
 */
const fluidFontSize = ({ addBase }) => {
  addBase({
    html: {
      fontSize: "clamp(16px, calc(1rem + ((1vw - 7.68px) * 0.7813)), 18px)",
    },
  });
};

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      fontFamily: {
        serif: ["Crimson Text", ...defaultTheme.fontFamily.serif],
      },
    },
  },
  plugins: [fluidFontSize, typography],
};
